'''author@esilgard'''
## global strings for output dictionaries ##
ERRS = "errors"
REPORTS = "reports"
NAME = "name"
TABLE = "table"
TABLES = "tables"
VALUE = "value"
FIELDS = "fields"
REPORT = "report"
MRN = "mrn"
MRN_CAPS = "MRN"
CONFIDENCE = "confidence"
VERSION = "algorithmVersion"
STARTSTOPS = "startStops"
KEY = "recordKey"
START = "startPosition"
STOP = "stopPosition"
ERR_STR = "errorString"
ERR_TYPE = "errorType"
ALL = "ALL"
OBSERVATION_VALUE = "ObservationValue"
FILLER_ORDER_NO = "FillerOrderNo"
EVENT_DATE = "EventDate"
