## global strings for output dictionaries ##
NAME="name"
TABLE="table"
VALUE="value"
CONFIDENCE="confidence"
VERSION="algorithmVersion"
STARTSTOPS="startStops"
KEY="recordKey"
START="startPosition"
STOP="stopPosition"
