## global strings for output dictionaries (cytogenetics, aml specific ##
NAME="name"
TABLE="table"
VALUE="value"
FIELDS="fields"
REPORT="report"
KARYO="karyotype"
KARYOTYPE_STRING="KaryotypeString"
CONFIDENCE="confidence"
VERSION="algorithmVersion"
STARTSTOPS="startStops"
KEY="recordKey"
START="startPosition"
STOP="stopPosition"
ERR_STR="errorString"
ERR_TYPE="errorType"
INSUFFICIENT="Insufficient"
MISCELLANEOUS="Miscellaneous"
INTERMEDIATE="Intermediate"
UNFAVORABLE="Unfavorable"
FAVORABLE="Favorable"
CELL_COUNT="CellCount"
ABNORMALITIES="Abnormalities"
WARNING="Warning"
AML_CYTOGENETICS="AML_Cytogenetics"
SWOG="AML_SWOG_RiskCategory"
UNKNOWN="Unknown"

