# Event Filler Features
ATTRIB_GRAM = "ATTRIB_GRAM_"
ATTRIB_TYPE = "ATTRIB_TYPE_"
CURRENT_SENT_EVENT_TYPE = "CURR_SENT_HAS_EVENT_"
PREV_SENT_EVENT_TYPE = "PREV_SENT_HAS_EVENT_"
SURR_WORD = "SURR_WORD_"
CLOSEST_LEFT_KEYWORD = "CLOSEST_LEFT_KEYW_"
CLOSEST_RIGHT_KEYWORD = "CLOSEST_RIGHT_KEYW_"
